### ISSUE TITLE
这是什么鬼

### ISSUE THREAD

**Issue by AtarisMio** [Gizeta/i-want-to-use-kancollecacher-and-kcsp-on-poi#1]
这名字也太谐了233333333

**Comment by Gizeta** [comment]
poi官方又不支持改包，而我又想用防猫+全图鉴。
名字怪一点儿就不会被发现哦233333

**Comment by Gizeta** [comment]
名字太长了，还是改名了_(:3」∠)_
poi-plugin-iwukkp
快去下载吧，扔掉你的Progit，换上ss-windows
233333333

**Comment by JenningsWu** [comment]
![8jhfzpxec 1bajp u6 sjex](https://cloud.githubusercontent.com/assets/6861365/13371763/e2f82d82-dce2-11e5-86f9-77750a6aa9ac.jpg)
