### ISSUE TITLE
一种另外的 proxy 实现方法

### ISSUE THREAD

**Issue by JenningsWu** [Gizeta/i-want-to-use-kancollecacher-and-kcsp-on-poi#2]
### 目前的实现是：
- 保留旧的 proxy，但关掉 server
- 创建新的 proxy，server 监听端口
- 在旧 proxy 上 emit 事件，同时将对新 proxy 的事件监听操作转到旧 proxy 上，保持行为一致
### 另一种实现方法：
- 不创建新的 proxy
- 关掉旧 server，在 proxy 里开个新的魔改代码的 server

**Comment by Gizeta** [comment]
想了想，两种方法在代码量上貌似没有差别，或许在资源性能上后一种更优。
感谢建议。
