### ISSUE TITLE
请教如何使用

### ISSUE THREAD

**Issue by cocoasoda** [Gizeta/i-want-to-use-kancollecacher-and-kcsp-on-poi#4]
插件安装成功之后填入了自己的服务器和端口号，然而不知道如何设置 poi 的代理

**Comment by Gizeta** [comment]
kcsp的服务器不是通常的代理，只会处理舰娘的api请求。
所以正常使用是需要一个日本代理的或改hosts的。

有日本代理要填在poi的代理页面里（改hosts的话一般就不用使用代理了）。
kcsp的服务器地址端口填在插件里。

**Comment by cocoasoda** [comment]
了解了，谢谢
